# Generated by Django 3.1.8 on 2021-05-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='counstInStock',
            new_name='countInStock',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
